/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class HierarchicalShiftAudioProcessorEditor  : public AudioProcessorEditor,
public ButtonListener,
public ChangeListener,
public SliderListener
{
public:
    HierarchicalShiftAudioProcessorEditor (HierarchicalShiftAudioProcessor&);
    ~HierarchicalShiftAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    
    void changeListenerCallback(ChangeBroadcaster* source) override;
    
    ToggleButton record;
    ToggleButton mute;
    Slider numSteps;
    TabbedButtonBar generateStyle;
    HierarchicalShiftAudioProcessor * getProcessor();
    void buttonClicked(Button *b) override;
    void sliderValueChanged(Slider *) override;
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    HierarchicalShiftAudioProcessor& processor;
    
    ScopedPointer<LookAndFeel> myLookNFeel;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (HierarchicalShiftAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
